### ISSUE TITLE
大佬，你好，大佬有机会出一个mac版的工具，理由是flutter开发，mac开发者的数量非常多。

### ISSUE THREAD

**Issue by WangYiOS** [shAdow-XJY/subFontPackage#1]
如题所示，

祝大佬度过愉快美好的每一天。

**Comment by shAdow-XJY** [comment]
emmm这个我自己没有mac，而且其实本质是用了python的文件库，项目只是做了个提取文字，然后作为参数传入python运行而已。
只是为了剔除使用的时候需要安装python的环境，将这个库的功能也打包成一个可运行的程序。
我周末看看Python代码有没有上传上去，到时跟你说其实是运行哪份文件。

---Original---
From: ***@***.***&gt;
Sent at: 2023年10月13日(Fri) Noon11:02
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [shAdow-XJY/subFontPackage] 大佬，你好，大佬有机会出一个mac版的工具，理由是flutter开发，mac开发者的数量非常多。 (Issue #1)




 
如题所示，
 
祝大佬度过愉快美好的每一天。

**Comment by shAdow-XJY** [comment]
已加Mac OS
